/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as ModelsImport } from './routes/models'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as DashboardLayoutUsageImport } from './routes/dashboard/_layout/usage'
import { Route as DashboardLayoutSettingsImport } from './routes/dashboard/_layout/settings'
import { Route as DashboardLayoutProviderKeysImport } from './routes/dashboard/_layout/provider-keys'
import { Route as DashboardLayoutModelsImport } from './routes/dashboard/_layout/models'
import { Route as DashboardLayoutApiKeysImport } from './routes/dashboard/_layout/api-keys'
import { Route as DashboardLayoutActivityImport } from './routes/dashboard/_layout/activity'
import { Route as DashboardLayoutSettingsIndexImport } from './routes/dashboard/_layout/settings/index'
import { Route as DashboardLayoutSettingsSecurityImport } from './routes/dashboard/_layout/settings/security'
import { Route as DashboardLayoutSettingsPreferencesImport } from './routes/dashboard/_layout/settings/preferences'
import { Route as DashboardLayoutSettingsBillingImport } from './routes/dashboard/_layout/settings/billing'
import { Route as DashboardLayoutSettingsAdvancedImport } from './routes/dashboard/_layout/settings/advanced'
import { Route as DashboardLayoutSettingsAccountImport } from './routes/dashboard/_layout/settings/account'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const ModelsRoute = ModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutUsageRoute = DashboardLayoutUsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutSettingsRoute = DashboardLayoutSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutProviderKeysRoute =
  DashboardLayoutProviderKeysImport.update({
    id: '/provider-keys',
    path: '/provider-keys',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutModelsRoute = DashboardLayoutModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutApiKeysRoute = DashboardLayoutApiKeysImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutActivityRoute = DashboardLayoutActivityImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutSettingsIndexRoute =
  DashboardLayoutSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

const DashboardLayoutSettingsSecurityRoute =
  DashboardLayoutSettingsSecurityImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

const DashboardLayoutSettingsPreferencesRoute =
  DashboardLayoutSettingsPreferencesImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

const DashboardLayoutSettingsBillingRoute =
  DashboardLayoutSettingsBillingImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

const DashboardLayoutSettingsAdvancedRoute =
  DashboardLayoutSettingsAdvancedImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

const DashboardLayoutSettingsAccountRoute =
  DashboardLayoutSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardLayoutSettingsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/activity': {
      id: '/dashboard/_layout/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardLayoutActivityImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/api-keys': {
      id: '/dashboard/_layout/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardLayoutApiKeysImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/models': {
      id: '/dashboard/_layout/models'
      path: '/models'
      fullPath: '/dashboard/models'
      preLoaderRoute: typeof DashboardLayoutModelsImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/provider-keys': {
      id: '/dashboard/_layout/provider-keys'
      path: '/provider-keys'
      fullPath: '/dashboard/provider-keys'
      preLoaderRoute: typeof DashboardLayoutProviderKeysImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/usage': {
      id: '/dashboard/_layout/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardLayoutUsageImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/settings/account': {
      id: '/dashboard/_layout/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardLayoutSettingsAccountImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
    '/dashboard/_layout/settings/advanced': {
      id: '/dashboard/_layout/settings/advanced'
      path: '/advanced'
      fullPath: '/dashboard/settings/advanced'
      preLoaderRoute: typeof DashboardLayoutSettingsAdvancedImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
    '/dashboard/_layout/settings/billing': {
      id: '/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardLayoutSettingsBillingImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
    '/dashboard/_layout/settings/preferences': {
      id: '/dashboard/_layout/settings/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/preferences'
      preLoaderRoute: typeof DashboardLayoutSettingsPreferencesImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
    '/dashboard/_layout/settings/security': {
      id: '/dashboard/_layout/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardLayoutSettingsSecurityImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
    '/dashboard/_layout/settings/': {
      id: '/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardLayoutSettingsIndexImport
      parentRoute: typeof DashboardLayoutSettingsImport
    }
  }
}

// Create and export the route tree

interface DashboardLayoutSettingsRouteChildren {
  DashboardLayoutSettingsAccountRoute: typeof DashboardLayoutSettingsAccountRoute
  DashboardLayoutSettingsAdvancedRoute: typeof DashboardLayoutSettingsAdvancedRoute
  DashboardLayoutSettingsBillingRoute: typeof DashboardLayoutSettingsBillingRoute
  DashboardLayoutSettingsPreferencesRoute: typeof DashboardLayoutSettingsPreferencesRoute
  DashboardLayoutSettingsSecurityRoute: typeof DashboardLayoutSettingsSecurityRoute
  DashboardLayoutSettingsIndexRoute: typeof DashboardLayoutSettingsIndexRoute
}

const DashboardLayoutSettingsRouteChildren: DashboardLayoutSettingsRouteChildren =
  {
    DashboardLayoutSettingsAccountRoute: DashboardLayoutSettingsAccountRoute,
    DashboardLayoutSettingsAdvancedRoute: DashboardLayoutSettingsAdvancedRoute,
    DashboardLayoutSettingsBillingRoute: DashboardLayoutSettingsBillingRoute,
    DashboardLayoutSettingsPreferencesRoute:
      DashboardLayoutSettingsPreferencesRoute,
    DashboardLayoutSettingsSecurityRoute: DashboardLayoutSettingsSecurityRoute,
    DashboardLayoutSettingsIndexRoute: DashboardLayoutSettingsIndexRoute,
  }

const DashboardLayoutSettingsRouteWithChildren =
  DashboardLayoutSettingsRoute._addFileChildren(
    DashboardLayoutSettingsRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardLayoutActivityRoute: typeof DashboardLayoutActivityRoute
  DashboardLayoutApiKeysRoute: typeof DashboardLayoutApiKeysRoute
  DashboardLayoutModelsRoute: typeof DashboardLayoutModelsRoute
  DashboardLayoutProviderKeysRoute: typeof DashboardLayoutProviderKeysRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRouteWithChildren
  DashboardLayoutUsageRoute: typeof DashboardLayoutUsageRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutActivityRoute: DashboardLayoutActivityRoute,
  DashboardLayoutApiKeysRoute: DashboardLayoutApiKeysRoute,
  DashboardLayoutModelsRoute: DashboardLayoutModelsRoute,
  DashboardLayoutProviderKeysRoute: DashboardLayoutProviderKeysRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRouteWithChildren,
  DashboardLayoutUsageRoute: DashboardLayoutUsageRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/models': typeof DashboardLayoutModelsRoute
  '/dashboard/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRouteWithChildren
  '/dashboard/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/settings/advanced': typeof DashboardLayoutSettingsAdvancedRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/settings/': typeof DashboardLayoutSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/models': typeof DashboardLayoutModelsRoute
  '/dashboard/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/settings/advanced': typeof DashboardLayoutSettingsAdvancedRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/activity': typeof DashboardLayoutActivityRoute
  '/dashboard/_layout/api-keys': typeof DashboardLayoutApiKeysRoute
  '/dashboard/_layout/models': typeof DashboardLayoutModelsRoute
  '/dashboard/_layout/provider-keys': typeof DashboardLayoutProviderKeysRoute
  '/dashboard/_layout/settings': typeof DashboardLayoutSettingsRouteWithChildren
  '/dashboard/_layout/usage': typeof DashboardLayoutUsageRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/settings/account': typeof DashboardLayoutSettingsAccountRoute
  '/dashboard/_layout/settings/advanced': typeof DashboardLayoutSettingsAdvancedRoute
  '/dashboard/_layout/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/_layout/settings/preferences': typeof DashboardLayoutSettingsPreferencesRoute
  '/dashboard/_layout/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/_layout/settings/': typeof DashboardLayoutSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/api-keys'
    | '/dashboard/models'
    | '/dashboard/provider-keys'
    | '/dashboard/settings'
    | '/dashboard/usage'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/advanced'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/api-keys'
    | '/dashboard/models'
    | '/dashboard/provider-keys'
    | '/dashboard/usage'
    | '/dashboard/settings/account'
    | '/dashboard/settings/advanced'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/models'
    | '/onboarding'
    | '/signup'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/_layout/activity'
    | '/dashboard/_layout/api-keys'
    | '/dashboard/_layout/models'
    | '/dashboard/_layout/provider-keys'
    | '/dashboard/_layout/settings'
    | '/dashboard/_layout/usage'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/settings/account'
    | '/dashboard/_layout/settings/advanced'
    | '/dashboard/_layout/settings/billing'
    | '/dashboard/_layout/settings/preferences'
    | '/dashboard/_layout/settings/security'
    | '/dashboard/_layout/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/models",
        "/onboarding",
        "/signup",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/models": {
      "filePath": "models.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/activity",
        "/dashboard/_layout/api-keys",
        "/dashboard/_layout/models",
        "/dashboard/_layout/provider-keys",
        "/dashboard/_layout/settings",
        "/dashboard/_layout/usage",
        "/dashboard/_layout/"
      ]
    },
    "/dashboard/_layout/activity": {
      "filePath": "dashboard/_layout/activity.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/api-keys": {
      "filePath": "dashboard/_layout/api-keys.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/models": {
      "filePath": "dashboard/_layout/models.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/provider-keys": {
      "filePath": "dashboard/_layout/provider-keys.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/settings": {
      "filePath": "dashboard/_layout/settings.tsx",
      "parent": "/dashboard/_layout",
      "children": [
        "/dashboard/_layout/settings/account",
        "/dashboard/_layout/settings/advanced",
        "/dashboard/_layout/settings/billing",
        "/dashboard/_layout/settings/preferences",
        "/dashboard/_layout/settings/security",
        "/dashboard/_layout/settings/"
      ]
    },
    "/dashboard/_layout/usage": {
      "filePath": "dashboard/_layout/usage.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/": {
      "filePath": "dashboard/_layout/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/settings/account": {
      "filePath": "dashboard/_layout/settings/account.tsx",
      "parent": "/dashboard/_layout/settings"
    },
    "/dashboard/_layout/settings/advanced": {
      "filePath": "dashboard/_layout/settings/advanced.tsx",
      "parent": "/dashboard/_layout/settings"
    },
    "/dashboard/_layout/settings/billing": {
      "filePath": "dashboard/_layout/settings/billing.tsx",
      "parent": "/dashboard/_layout/settings"
    },
    "/dashboard/_layout/settings/preferences": {
      "filePath": "dashboard/_layout/settings/preferences.tsx",
      "parent": "/dashboard/_layout/settings"
    },
    "/dashboard/_layout/settings/security": {
      "filePath": "dashboard/_layout/settings/security.tsx",
      "parent": "/dashboard/_layout/settings"
    },
    "/dashboard/_layout/settings/": {
      "filePath": "dashboard/_layout/settings/index.tsx",
      "parent": "/dashboard/_layout/settings"
    }
  }
}
ROUTE_MANIFEST_END */
